// DadJokesVue/src/App.vue
<template>
  <div class="bg-slate-100">
    <NavBar />
    <main class='h-[calc(100vh-48px-56px)] flex flex-col items-center justify-center px-4 lg:px-0 '>
      <div class='container'>
        <JokesList />
      </div>
    </main>
    <AppFooter />
  </div>
</template>

<script >
import NavBar from "./components/NavBar.vue"
import AppFooter from "./components/Footer.vue"
import JokesList from "./components/JokesList.vue"
import { mapActions } from "vuex";

export default {
  name: "App",
  components: { NavBar, AppFooter, JokesList },
  methods: {
    ...mapActions("jokes", ["getJoke"])
  },
  created() {
    this.getJoke()
  }
}

</script>

// TodoReactTS/src/App.tsx
import { CreateTodo } from './components/CreateTodo';
import { Footer } from './components/Footer';
import { NavBar } from './components/NavBar';
import { TodoList } from './components/TodoList';

export const App = () => {
  return (
    <div className='bg-slate-100'>
      <NavBar />
      <main className='h-[calc(100vh-48px-56px)] flex flex-col items-center justify-center px-4 lg:px-0'>
        <div className='container'>
          <CreateTodo />
          <TodoList />
        </div>
      </main>
      <Footer />
    </div>
  )
}
